#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="kopia"

if pgrep -f kopia &> /dev/null 2>&1; then
    print_info "Gracefully shutting down Kopia Server"
    kopia server --address 127.0.0.1:"${LISTEN_PORT}" --server-control-username="${SERVER_ADMIN_USER}" --server-control-password="${SERVER_ADMIN_PASS}" shutdown
fi
